version: "3"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - my_db:/data/db
    networks:
      - my_network

volumes:
  my_db:

networks:
  my_network:
    driver: bridge
